In [2]:

# From Python Lists
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr_2d)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [5]:
# Special Arrays
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.24926365 0.88223631]
 [0.72448324 0.61567799]
 [0.27151479 0.58406771]]
[[-1.08198902 -0.44026826]
 [ 0.30730098 -0.46562856]
 [ 0.55168943 -0.82962953]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [6]:
# Basic Math
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(np.sin(a))


[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [7]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A @ B)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [8]:
# Aggregation
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())


10
2.5
4
1
1.118033988749895


In [9]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[::2])


1
[2 3 4]
[1 3 5]


In [10]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])


2
[2 5]
[4 5]


In [11]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(arr[mask])


[4 5]


In [13]:
# Reshape
arr = np.arange(6)
print(arr.reshape(2, 3))


[[0 1 2]
 [3 4 5]]


In [14]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))


[1 2 3 4]


In [15]:
# Stacking
print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[1 2]
 [3 4]]
[1 2 3 4]


In [17]:
#broadcasting
a = np.array([1, 2, 3])
a + 5  


array([6, 7, 8])

In [18]:
# Save to a file
np.save('array.npy', arr)


In [19]:
# Load from a file
loaded_arr = np.load('array.npy')
